### PR TITLE
Fix various typos, switch URLs to https

### PR DESCRIPTION
**Pull request by JesseWeinstein**
Also add a few missing words and make some minor rephrasings and clarifications

### CODE REVIEW

**Comment by JesseWeinstein** [comment]
I need to make a PR to https://github.com/internetarchive/wayback also, but it's diverged from this, so I'll need to merge manually first.

**Comment by kris-sigur** [comment]
It would probably make more sense to move the bulk of this content to our wiki.

**Comment by JesseWeinstein** [comment]
This wiki? https://github.com/iipc/openwayback/wiki

**Comment by JesseWeinstein** [comment]
What's the status on this PR? Should I make a page on the wiki mentioned above, and merge the content there, or do something else?

**Comment by kris-sigur** [comment]
Merged. It is an improvement. We should however, as part of #261, improve on this and move it to the wiki along with all the other documentation.

**Pull request merged**
