### PR TITLE
Bubble calendar mouse-wheeled horizontal scrollbar for year chart

### LINKED ISSUE #214: In BubbleCalendar, year chart increases horizontally every year
bubblecalendar ui issue

It is noticed in the bubble calendar format that year numbers are not at the same line with year chart. They are shifted one line down, because page width doesn't fit with the increasing number of years. So for each year added to the chart, page width should be increased, which is not practical. We have to find away to fix such issue as shown above.

### PR DESCRIPTION
**Pull request by MohammedElsayyed**
Fix #214: placing the year chart inside a mouse-wheeled horizontal scrollbar in bubble calendar web page. This is as solution instead of decreasing year image width in the beginning of every new year to fit inside the page.

### CODE REVIEW

**Comment by MohammedElsayyed** [comment]
The following is screenshots of mouse-wheeled horizontal scrollbar for the year chart:




We will deploy it on BA cluster later this week or the beginning of next week. If so, I will provide you with a URL to give it a try!

**Comment by MohammedElsayyed** [comment]
Installed it on BA cluster. If you are interested in giving it a try, please make sure the following features are working properly:

- Scroll via mouse wheel, but make sure mouse pointer is hovering over year chart.
- Scroll via keyboard. The left arrow key and right arrow key cause the thumb of the slider to go left and right, respectively. Please make sure that the slider has the focus (it’s the currently selected GUI component.)
- Swipe scrolling on touch-enabled devices.

The following is a URL in BA collection:
http://web.archive.bibalex.org/web/*/http://cnn.com

BTW, touch-swipe scrolling is working as expected on touch-enabled devices. I tested it on Samsung Galaxy Note 10.1 (release 2014).

**Comment by gmj2053** [comment]
We tested here at LC and it looks great.  I have some new help, Chase Dooley, @chasehd, who will be on next call.

**Comment by ldko** [comment]
Closing this, since it was handled with #332.

**Pull request closed without merging**
