### PR TITLE
Fix for issue #256

### LINKED ISSUE #256: Display # of snapshots of a selected year in BubbleCalendar
When a user searchs for a URL in OpenWayback, it might be interesting if we provide him how many snapshots have been taken for a specific URL in a particular (selected) year. This information will be next to total number of snapshots in a bubble calendar view.

### PR DESCRIPTION
**Pull request by MohammedElsayyed**
Resolves #256. These changes will display # of snapshots of a selected year in bubble canledar view. This piece of information will be provided beside the total number of snapshots.

### CODE REVIEW

**Comment by kris-sigur** [comment]
Not sure about localization of the added text.

**Comment by mody1first** [comment]
I agree to add 'times in' in WaybackUI.properties instead of hard-coding it in BubbleCalendar.jsp.

BTW, how about renaming it to be OpenWaybackUI.properties?

**Comment by MohammedElsayyed** [comment]
I agree to add 'times in' in WaybackUI.properties instead of hard-coding it in BubbleCalendar.jsp.

BTW, how about renaming it to OpenWaybackUI.properties?

**Comment by kris-sigur** [comment]
Renaming the file may break existing WAR overlays.

**Pull request merged**
